### PR TITLE
Add simulation for model with swerve wheels

### PR DESCRIPTION
**Pull request by nlamprian**
image

### CODE REVIEW

**Comment by dylanvaughn** [comment]
@nlamprian sorry for the delay on this - when I run `make bringup` I get this error:

```
dylan@dcv-thinkpad:~/src/rm/forks/nlamprian/pvc-powerchair$ make bringup
docker build --network=host -t devenv:latest .
Sending build context to Docker daemon   84.3MB
Step 1/12 : FROM ros:noetic
 ---> 078ae756058f
Step 2/12 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> a290f2430eb6
Step 3/12 : RUN apt-get update && apt-get install -q -y         curl          gedit         git           gnupg         groff         jq            less          nano          tree          unzip         vim           wget          && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 3d985be06154
Step 4/12 : RUN wget http://packages.osrfoundation.org/gazebo.key
 ---> Using cache
 ---> a604e2854f26
Step 5/12 : RUN apt-key add gazebo.key
 ---> Using cache
 ---> aed20b53bf59
Step 6/12 : RUN apt-get update && apt-get install -y             python3-apt                                  python3-colcon-common-extensions             python3-pip                                  python3-vcstool                              ros-noetic-cob-undercarriage-ctrl            ros-noetic-desktop-full                      ros-noetic-gazebo-ros-control                ros-noetic-teleop-tools                      ros-noetic-teleop-twist-keyboard             && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 18d9414c01cf
Step 7/12 : RUN rosdep update
 ---> Using cache
 ---> e1e61363840a
Step 8/12 : WORKDIR /software
 ---> Using cache
 ---> a50ff53706f9
Step 9/12 : ENV DEBIAN_FRONTEND=newt
 ---> Using cache
 ---> 516df6748311
Step 10/12 : COPY docker-entrypoint.sh /
 ---> Using cache
 ---> eee4167c89da
Step 11/12 : ENTRYPOINT ["/docker-entrypoint.sh"]
 ---> Using cache
 ---> d92942a57192
Step 12/12 : CMD ["bash"]
 ---> Using cache
 ---> 91e0c24ae71f
Successfully built 91e0c24ae71f
Successfully tagged devenv:latest
xhost +local:docker
non-network local connections being added to access control list
docker run -it --rm --privileged --net=host --volume /home/dylan/src/rm/forks/nlamprian/pvc-powerchair/software:/software --env=DISPLAY --env=QT_X11_NO_MITSHM=1 -v /tmp/.X11-unix:/tmp/.X11-unix devenv:latest bash -c "roslaunch pvcchair_bringup_sim robot.launch"
... logging to /root/.ros/log/fecc7fea-765c-11eb-b86e-a0c589b6247f/roslaunch-dcv-thinkpad-1.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: The following package was not found in <arg name="world_name" default="$(find aws_robomaker_small_house_world)/worlds/small_house.world"/>: aws_robomaker_small_house_world
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/software/src
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file
make: *** [Makefile:19: bringup] Error 1
dylan@dcv-thinkpad:~/src/rm/forks/nlamprian/pvc-powerchair$ 
```

what do you think?

**Comment by nlamprian** [comment]
You need to run the [rosws command](https://github.com/robomakery/pvc-powerchair/pull/81/files#diff-a827e5b83be5f3e3082ae3e6f8200c8a2523fefeb3ad5873e3065f0854a1a03dR7) in the Dockerfile.

You could also get rid of the list of noetic dependencies, but just running the rosdep command as well.

Do you mind taking care of it?

**Comment by dylanvaughn** [comment]
@nlamprian I get this error when trying to run the `rosws` command:

```
root@dcv-thinkpad:/software# rosws update -t src
ERROR in config: /software/src has no workspace configuration file '.rosinstall'
root@dcv-thinkpad:/software# 
```

Where is the `.rosinstall` file?

**Comment by nlamprian** [comment]
Sorry about that, added

**Pull request merged**
